---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "app.fullname" . }}-config
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  appsettings.json: |-
    {
      "AWS": {
        "ServiceUrl": "http://{{ .Values.infra.minio.url }}",
        "AccessKeyId": "{{ .Values.infra.minio.access_key }}",
        "SecretAccessKey": "{{ .Values.infra.minio.secret_key }}"
      },
      "ConnectionStrings": {
        "TaxPaymentRefund": "{{ .Values.infra.postgresql.tax_payment_refund }}",
        "LongTermDeduplicationService": "{{ .Values.infra.postgresql.long_term_deduplication }}",
        "Reference": "{{ .Values.infra.oracle.mdm_local }}"
      },
      "Deduplication": {
        "ConnectionString": "{{ .Values.infra.redis.url }}",
        "SlidingExpirationHours": 24
      },
      "Kafka": {
        "Uri": "{{ .Values.infra.kafka.url }}",
        "Consumer": {
          "GroupId": "{{ include "app.fullname" . }}"
        }
      },
      "Logging": {
        "LogLevel": {
          "CorrelationId.CorrelationIdMiddleware": "Warning",
          "Microsoft.Extensions.Diagnostics.HealthChecks": "Warning"
        }
      },
      "NLogExtraConfig": {
        "min_level": "{{ .Values.log_level }}"
      },
      
      "Refit": {
        "TimeoutSeconds": {{ .Values.refit.timeout_seconds }}
      },
      
      "OpenTelemetry": {
        "OtlpEndpointUrl": "{{ .Values.infra.jaeger.url }}"
      },
      
      "PowerOfAttorney": {
        "CheckPowerOfAttorneyApiUrl": "{{ .Values.external.power_of_attorney.url }}"
      },

      "Reorganization": {
        "ApiUrl": "{{ .Values.external.reorganization.url }}"
      },

      "SubsytemTaxPaymentRefund": {
        "InputTopic1112542": "1112542",
        "InputTopic1165166": "1165166",
        "InputTopic1122029": "1122029",
        "InputTopic1122030": "1122030",
        "InputTopic1150057": "1150057",
        "InputTopic1150058": "1150058",

        "ConsumerNumber": 1,
        "ErrorTopic": "_error",
        "RetryCount": 3,
        "DisableBusinessDeduplication": true,
        "PersistedTaskDelays": {
          "NextTryPowerOfAttorneyDelayMinutes": 120,
          "NextTrySendResultStateDelayMinutes": 120,
          "NextTryOnErrorDelayMinutes": 120,
          "NextTryOnErrorDelayMaxMinutes": 7200,
          "PowerOfAttorneyMaxWaitDays": 30
        },
        "PersistedTaskLoopDelays": {
          "WithErrorWaitLoopDelaySeconds": 30,
          "SubsystemWaitLoopDelaySeconds": 30,
          "PowerOfAttorneyWaitLoopDelaySeconds": 30
        }
      },

      "TaxpayerAccounting": {
        "FindWtFlServiceApiUrl": "{{ .Values.external.taxpayer_accounting.findwtfserviceurl }}",
        "FindWtUlServiceApiUrl": "{{ .Values.external.taxpayer_accounting.findwtuserviceurl }}",
        "FindWtIoServiceApiUrl": "{{ .Values.external.taxpayer_accounting.findwtiserviceurl }}"
      },

      "TaxpayerIdentification": {
        "TaxCodeByAddressFor1And101Open101ApiUrl":  "{{ .Values.external.taxpayer_identification.TaxCodeByAddressFor1And101Open101Url }}",
        "TaxCodeByAddressFor1And101ApiUrl":  "{{ .Values.external.taxpayer_identification.TaxCodeByAddressFor1And101Url }}",
        "TaxCodeByAddressOtherApiUrl":  "{{ .Values.external.taxpayer_identification.TaxCodeByAddressOtherUrl }}",
        "Tax3PersonIdentificationApiUrl":  "{{ .Values.external.taxpayer_identification.Tax3PersonIdentificationUrl }}",
        "Tax3ForeignIdentificationApiUrl":  "{{ .Values.external.taxpayer_identification.Tax3ForeignIdentificationUrl }}",
        "Tax3LegalIdentificationApiUrl":  "{{ .Values.external.taxpayer_identification.Tax3LegalIdentificationUrl }}",
        "PonilIdentificationApiUrl":  "{{ .Values.external.taxpayer_identification.PonilIdentificationUrl }}",
        "UnionTaxpayerApiUrl":  "{{ .Values.external.taxpayer_identification.UnionTaxpayerUrl }}"
      },
    }