kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ include "app.fullname" . }}-pvc"
  namespace: {{ .Release.Namespace | quote }}  
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
