---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "app.fullname" . }}-version
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  index.html: |-
    {{ .Values.initContainers.liquibase.image.tag }}
