---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "app.fullname" . }}-secret-env
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  CLICKHOUSE_HOST: "{{ .Values.infra.clickhouse.host | b64enc }}"
  CLICKHOUSE_PORT: "{{ .Values.infra.clickhouse.port | toString | b64enc }}"
  CLICKHOUSE_USERNAME: "{{ .Values.infra.clickhouse.username | b64enc }}"
  CLICKHOUSE_PASSWORD: "{{ .Values.infra.clickhouse.password | toString | b64enc }}"
